spring:
  application:
    name: kafka-to-elastic-service
  profiles:
    active: kafka_to_elastic
  config:
    import: 'configserver:'
  cloud:
    config:
      name: kafka-to-elastic-service,config-client
      uri: http://localhost:8888
      username: spring_cloud_user
      password: 'Aman0081'

log:
  app-name: kafka-to-elastic-service

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}