spring:
  application:
    name: elastic-query-web-client-2
  profiles:
    active: elastic_query_web_2
  config:
    import: 'configserver:'
  cloud:
    config:
      name: elastic-query-web-client-2,config-client
      uri: http://localhost:8888
      username: spring_cloud_user
      password: 'Aman0081'

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service-1:8761/eureka/, http://discovery-service-2:8762/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2